Анимация + всякое
DihtGameDev/diht_team_6 pull request #2
Opened 2020-05-09 13:07 UTC by mikser22

Хотел уложиться в дедлайн по анимации, сделал игровое поле и добавил юнита. Управление и атаку еще не успел сделать. Анимация движения использовал из ассет стора. Для коробок делал анимационный клип сам. Но мои творческие способности не позволяют сделать сильно лучше чем то, что получилось. Тем не менее считаю что на 5 баллов за создание своих клипов этого хватит

Так же здесь использовались физика: rigit body и коллайдеры.

2020-05-11 17:00 UTC, mikser22 commented
Только щас понял, что нужно еще ревьюеров назначать

2020-05-17 21:00 UTC, chav0 requested changes

2020-05-17 21:00 UTC, chav0 commented on .gitignore
> +/Library
а можете где-нибудь нагуглить нормальный гитигнор?)

2020-05-17 21:00 UTC, chav0 commented on Assets/Scripts/Archer.cs
> +        rb = GetComponent<Rigidbody2D>();
Но ведь можно же его сделать [SerializeField]

2020-05-17 21:00 UTC, chav0 commented on Assets/downloadPacks/Joystick Pack/Scripts/Base/Joystick.cs
> +public class Joystick : MonoBehaviour, IPointerDownHandler, IDragHandler, IPointerUpHandler
Я думала, вы уже большие и будете сами код писать. Ну ладно, и так сойдет :)

2020-05-17 21:01 UTC, chav0 commented
Конфликт еще решите

2020-05-17 21:26 UTC, mikser22 commented on Assets/Scripts/Archer.cs
> +        rb = GetComponent<Rigidbody2D>();
Окей, пока не знаю что это, но я нагуглю

2020-05-21 17:01 UTC, chav0 approved these changes

2020-05-21 17:01 UTC, merged